#!/bin/sh

# update aur packages based on unofficial pacages listed in $pacman -Qqm

for x in $(pacman -Qqm)
do
  cd /tmp
  git clone https://aur.archlinux.org/$x
  cd /tmp/$x
  makepkg -si
  sudo rm -r /tmp/$x
  echo "=================="
  echo " "
done
