#!/usr/bin/sh
# script for updating maintained AUR packages

REPO=$HOME/git/pkgbuild

# pull source
read pkg_name
cd /tmp
git clone ssh://aur.archlinux.org/$pkg_name

NEWVER=cat /tmp/$pkg_name/.SRCINFO | grep pkgver | tail -c +11

# build, update source, rebuild
cd $pkg_name
makepkg -s
updpkgsums
makepkg -sfi
makepkg --printsrcinfo > .SRCINFO

# push update
gadd PKGBUILD .SRCINFO
gcom -m "updated version: $NEWVER"
git push

# copy to personal repo
cp {PKGBUILD, .SRCINFO} $REPO/$pkg_name/
cd $REPO
git add *
git com -m "$pkg_name: updated version: $NEWVER"
git push

# clean up
sudo rm -r /tmp/$pkg_name
