#!/bin/sh
# pull updates from AUR and build / install packages

mkdir -p /tmp/aur

for x in $(pacman -Qqm)
do
  cd /tmp/aur
  git clone https://aur.archlinux.org/$x
  cd $x
  makepkg -si
  sudo rm -r /tmp/aur/$x
done

rm -r /tmp/aur
