#!/bin/sh
# pull updates from AUR and build / install packages

mkdir -p /tmp/aur
cd /tmp/aur
pacman -Qm > old.aurversion

for x in $(pacman -Qqm)
do
  git clone https://aur.archlinux.org/$x
  cd $x
  makepkg -si
  cd /tmp/aur
done

# update update list

for x in $(pacman -Qqm)
do
  cd /tmp/aur
  # pull aur source
  git clone https://aur.archlinux.org/$x
  # get new versions
  echo $x\ $(cat $x/.SRCINFO | grep pkgver | tail -c +11)-$(cat $x/.SRCINFO | grep pkgrel | tail -c +11) >> /tmp/aur/new.aurversion
done

# compare versions
diff -y --suppress-common-lines old.aurversion new.aurversion > /tmp/aur.updates
