#!/bin/sh

USER=austin
USER_HOME=/home/$USER
KEY=$USER_HOME/vault/backup.keyfile
CRYPT=/dev/sdb1
DECRYPT=backup
DEST=/mnt
EXCLUDE=$USER_HOME/.config/user.exclude


#prep
sudo -u $USER ecryptfs-mount-private
cryptsetup open --key-file $KEY $CRYPT $DECRYPT
mount /dev/mapper/$DECRYPT $DEST

#save kernel modules to $HOME/.config/modprobed.db
modprobed-db store

#configurations
lsblk -f > $DEST/disk.structure

#sytem directories
echo "syncing /root................."
rsync -aAXv /root/ $DEST/root/
echo "syncing /boot................."
rsync -aAXv /boot/ $DEST/boot/
echo "syncing /etc.................."
rsync -aAXv /etc/ $DEST/etc/
echo "syncing /var.................."
rsync -aAXv /var/ $DEST/var/
echo "syncing /usr.................."
rsync -aAXv /usr/ $DEST/usr/

#user directories
echo "syncing /home/$USER..........."
rsync -aAXv --exclude-from=$EXCLUDE $USER_HOME/ $DEST/$USER_HOME

#switch to tar / compression if storage space is limited
#tar -cf - /root | xz -c -9 - > $DEST/root.tar.xz
#tar -cf - /boot | xz -c -9 - > $DEST/boot.tar.xz
#tar -cf - /etc | xz -c -9 - > $DEST/etc.tar.xz
#tar -cf - /var | xz -c -9 - > $DEST/var.tar.xz
#tar -cf --exclude-from=$EXCLUDE - $USER_HOME | xz -c -9 - > $DEST/home-$USER.tar.xz

#clean up
umount /mnt
cryptsetup close /dev/mapper/$DECRYPT
