#!/bin/zsh

#Filesystem defragment, scrub, blance
#find / -xdev -type d -print -exec btrfs filesystem defragment '{}' \;
#btrfs scrub start /								# verify checksums on metadata
#btrfs balance start /								# reorganize big data chunks

# Mirrorlist
pacman -Syy											# for refresh of all mirrors
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup					# backup mirrorlist
reflector --country 'United States' -l 50 -p http --sort rate --save /etc/pcman.d/mirrorlist	# 50 most recent sorted by speed
pacman -Syy											# sync to new mirrorlist

# Packages / Pacman
paccache -rk2			# keep most recent version of installed packages +1 downgrade
paccache -ruk0			# remove cached versions of unistalled packages

# Clean Journal
journalctl --vacuum-size=50M

# Clean Libraries
# likely modules from old kernel versions, missed by pacman because package wasn't uninstalled
# requires: lostfiles

#lostfiles > /tmp/lostfiles.txt
#for x in $(cat /tmp/lostfiles.txt | grep /usr/lib/modules)
#  rm -r $x

# Make Arch Usb
MIRROR=http://mirror.cs.pitt.edu/archlinux/iso
VERSION=$(date +%Y.%m).01)
USB=/dev/sdc
curl =-o /tmp/archlinux.iso $MIRROR/$VERSION/archlinux-$VERSION-x86_64.iso
dd bs=4M if=/tmp/archlinux.iso of=$USB && sync
rm /tmp/archlinux.iso
