#!/bin/zsh

#Filesystem defragment, scrub, blance
#find / -xdev -type d -print -exec btrfs filesystem defragment '{}' \;
#btrfs scrub start /								# verify checksums on metadata
#btrfs balance start /								# reorganize big data chunks

# Mirrorlist
pacman -Syy											# for refresh of all mirrors
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup					# backup mirrorlist
reflector --country 'United States' -l 50 -p http --sort rate --save /etc/pcman.d/mirrorlist	# 50 most recent sorted by speed
pacman -Syy											# sync to new mirrorlist

# Packages / Pacman
pacman-optimize
paccache -rk1			# keep most recent version of installed packages
paccache -ruk0			# remove cached versions of unistalled packages

# Local Backup
#mount /dev/sdd1 /mnt
#rsync -aAXv /boot/ /mnt/boot
#rsync -aAXv /{root,etc,var,usr} /mnt/root/
#rsync -aAXv /home/austin/ --exclude={.cache,.cache-bk}/ /mnt/home/austin/
#umount /mnt

# make arch usb
MIRROR=http://mirror.cs.pitt.edu/archlinux/iso
VERSION=$(date +%Y.%m).01)
USB=/dev/sdc
curl =-o /tmp/archlinux.iso $MIRROR/$VERSION/archlinux-$VERSION-x86_64.iso
dd bs=4M if=/tmp/archlinux.iso of=$USB && sync
rm /tmp/archlinux.iso
