#!/bin/sh
# make bootable USB

MIRROR=http://mirror.cs.pitt.edu/archlinux/iso
VERSION=$(date +%Y.%m).01
USB=/dev/sdc

curl -o /tmp/archlinux.iso $MIRROR/$VERSION/archlinux-$VERSION-x86_64.iso
dd bs=4M if=/tmp/archlinux.iso of=$USB && sync
rm /tmp/archlinux.iso

