#!/bin/sh
# backup, upgrade, and maintenance

# $HOME/scripts/shell/backup-onboot
sudo backup-onboot

# $HOME/scripts/shell/updmirrors
sudo updmirrors

# upgrade official packages
sudo pacman -Syu

# upgrade aur packages
mkdir -p /tmp/aur
auracle -C /tmp/aur update
# modify PKGBUILDs
#for pkg in {linux-ck}
#  do
#    if ls /tmp/aur/ | grep '$pkg'
#    then
#    nano /tmp/aur/$pkg/PKGBUILD
#    fi
#  done
if
  ls /tmp/aur | grep 'linux-ck'
  then
  nano /tmp/aur/linux-ck/PKGBUILD
fi

# build packages
for pkg in $(ls /tmp/aur)
  do
    cd /tmp/aur/$pkg
    makepkg -sfi
    sudo rm -r /tmp/aur/$pkg
  done

# install kernel modules
sudo dkms autoinstall
