#!/usr/bin/sh
# post web connection utilities

USER=austin
USER_HOME=/home/$USER
RCLONE="rclone --config=$USER_HOME/.config/rclone/rclone.conf"

# testing connection
ping -c 3 www.google.com
echo "--------------------"

# firewall
echo "establishing firewall..."
$USER_HOME/documents/vault/iptables.rules
echo "--------------------"

# fetch for conky
echo "fetching things for conky..."
curl -o /tmp/ipinfo ipinfo.io                                                                   # ip info
curl http://www.ipinfodb.com/index.php | grep postal | tail -c 12 | head -c 5 > /tmp/zip        # zip code
curl -o /tmp/forecast wttr.in/$(cat /tmp/zip)                                                   # forecast / weather
sudo $USER checkupdates > /tmp/off.updates							# check official updates
$USER_HOME/git/scripts/shell/aur-checkupdate							# check aur updates
echo "--------------------"

# create remote and local backups
echo "Creating Remote Backups..."
paccache -rk2 											# clean /var/cache/pacman/pkg leaving current and one old version
rm /boot/*fallback.img 										# need to make space for upgrades on /boot
$USER_HOME/git/scripts/backup-cloud								# rclone, mega, gdrive
$USER_HOME/git/scripts/backup-local								# rsync to USB

echo "--------------------"
# set bluelight blocking
# managed in .xinitrc
#LATITUDE=33.43
#LONGITUDE=-84.91
#/bin/redshift -l $LATITUDE:$LONGITUDE 
# misc alterations
$USER_HOME/git/scripts/shell/playlist-conversion #make android playlists compatible with linux filetree

# start local backup server
echo "Starting Syncthing Daemon..."
systemctl start syncthing@austin.service

# start mining crypto
#echo "Starting Minergate..."
#minergate-cli -u austin.haedicke@gmail.com --xmr 2
