#!/usr/bin/sh
# post web connection utilities

HOME=/home/austin
RCLONE="rclone --config=$HOME/.rclone.conf"

# testing connection
ping -c 3 www.google.com
echo "--------------------"

# firewall
echo "establishing firewall..."
$HOME/documents/vault/iptables.rules
echo "--------------------"

# fetch for conky
echo "fetching things for conky..."
curl -o /tmp/ipinfo ipinfo.io                                                                   # ip info
curl http://www.ipinfodb.com/index.php | grep postal | tail -c 12 | head -c 5 > /tmp/zip        # zip code
curl -o /tmp/forecast wttr.in/$(cat /tmp/zip)                                                   # forecast / weather
checkupdates > /tmp/off.updates                                                                 # official packages
echo "--------------------"

# create pc backup
echo "Creating PC Backup..."
pacman -Qqm > $HOME/mega/pc_backup/system/aur.pkglist
pacman -Qe > $HOME/mega/pc_backup/system/off.pkglist
tar -czf $HOME/mega/pc_backup/system/etc.tar.gz /etc
tar -czf $HOME/mega/pc_backup/system/boot.tar.gz /boot
tar --exclude={keys,vault} -czf $HOME/mega/pc_backup/$HOME/documents.tar.gz $HOME/documents
echo "--------------------"

# push to backups to Mega
echo "Pushing PC and Phone Backups to Mega..."
$RCLONE sync --ignore-existing $HOME/mega/pc_backup/ mega:/pc_backup/
$RCLONE sync --ignore-existing $HOME/mega/phone_backup/ mega:/phone_backup/
echo "--------------------"

# pulling from Google Drive
echo "Pulling  Google Drive ..."
$RCLONE sync gdrive_professional:/ $HOME/gdrive_professional/
$RCLONE sync gdrive_personal:/ $HOME/gdrive_personal/
echo "--------------------"

# start local backup server
echo "Starting Syncthing Daemon..."
systemctl start syncthing@austin.service

# start mining crypto
echo "Starting Minergate..."
minergate-cli -u austin.haedicke@gmail.com --xmr 2
