#!/usr/bin/sh
# post web connection utilities

USER=austin
USER_HOME=/home/$USER
RCLONE="rclone --config=$USER_HOME/.config/rclone/rclone.conf"

# testing connection
ping -c 3 www.google.com

# firewall
echo "------------------------"
echo "establishing firewall..."
echo "------------------------"
sudo systemctl start iptables

# fetch for conky (not needed with xfce-panel)
#sudo curl -o /tmp/ipinfo https://ipinfo.io
#curl -o /tmp/forecast wttr.in/$(cat /tmp/zip)                                                   # forecast / weather
#sudo -u $USER checkupdates > /tmp/off.updates							# check official updates
#$USER_HOME/scripts/shell/aur-checkupdate							# check aur updates
#echo "--------------------"

# change I/O scheduler (set on kernel line)
#sudo $USER_HOME/scripts/shell/changeio

# create backups
echo "-----------------------------"
echo "creating boot time backups..."
echo "-----------------------------"
#$USER_HOME/git/scripts/backup-cloud	
sudo $USER_HOME/scripts/shell/backup-onboot

# pull from google drive
rclone sync gdrive_personal:/ $USER_HOME/gdrive_personal/
rclone sync gdrive_counseling:/ $USER_HOME/gdrive_counseling/
rclone sync gdrive_k9:/ $USER_HOME/gdrive_k9/

# push phone backup and videos to mega
rclone sync $USER_HOME/mega/videos mega:/videos/; rclone cleanup mega:/
rclone sync $USER_HOME/mega/backup-phone/ mega:/backup-phone/; rclone cleanup mega:/

# system maintenance
echo "--------------------------"
echo "maintenance and cleanup..."
echo "--------------------------"
sudo $USER_HOME/scripts/shell/maintenance

echo "--------------------"
echo "Converting android playlists to linux filestructure..."
# make android playlists compatible with linux filetree
$USER_HOME/scripts/shell/playlist-conversion
# start local backup server
echo "Starting Syncthing Daemon..."
systemctl start syncthing@austin.service
# enable bluelight blocking
echo "Enableing bluelight blocking..."
sudo -u $USER redshift
